# Site
name: "Gastón Abril Rotger"
title: "Bitácora de un fotógrafo atormentado"
description: "Bitácora de un fotógrafo atormentado."
logo: 'assets/images/logo.png'
logo_hover: 'assets/images/logo_hover.png'
favicon: 'assets/images/favicon.ico'
baseurl: ""
google_analytics: 'G-NVPD0CPCVS'
include: ["_pages"]
permalink: /:title/
email: hello@gastonabril.com.ar

# Gitcus - Check https://giscus.app to get your Repo-IDs 
# Copy the "Enable giscus" section from giscus.app into gitcus.html file
# "enabled" or "disabled"
gitcus: "enabled"

#Footer
socials:
  personal_web: https://gastonabril.com.ar
  mastodon: https://mastodon.social/@ludomatic
  twitter: https://twitter.com/ludomatic
  instagram: https://instagram.com/ludomatic
  github: https://github.com/lud0matic

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jemoji  
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

# RSS

feed_items: 10
feed_update_period: daily
feed_update_frequency: 1